version: '3'
services:
    flask_app:
        build: .
        ports:
            - 5000:5000
        volumes: 
            - ./data:/code/data
        environment: 
            FLASK_APP: app.py
            FLASK_ENV: development
            FLASK_RUN_HOST: 0.0.0.0